---
language: python
services: docker

env:
  global:
    - ROLE_NAME: xymon-client
    - SCENARIO: default
    - SCENARIO: default-debian_stretch

install:
  # Install test dependencies.
  - pip install molecule docker

script: |
  # Run tests with molecule.
  if [ "${SCENARIO}" == "default" ]; then
    molecule test
  else
    molecule test -s "${SCENARIO}"
  fi
