---
language: python
services: docker

env:
  global:
    - ROLE_NAME: xymon-client

install:
  # Install test dependencies.
  - pip install molecule docker

script:
  # Run tests with molecule.
  - molecule test
